{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceChanged","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Error"]]},"identifier":{"url":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Error\/FaceChanged","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","modules":[{"name":"self_ios_sdk"}],"symbolKind":"case","title":"LivenessCheck.Error.FaceChanged","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceChanged"}],"externalID":"s:12self_ios_sdk13LivenessCheckC5ErrorO11FaceChangedyA2EmF","role":"symbol"},"variants":[{"paths":["\/documentation\/self_ios_sdk\/livenesscheck\/error\/facechanged"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/Error":{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Error","type":"topic","role":"symbol","title":"LivenessCheck.Error","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/livenesscheck\/error"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/Error/FaceChanged":{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Error\/FaceChanged","kind":"symbol","url":"\/documentation\/self_ios_sdk\/livenesscheck\/error\/facechanged","type":"topic","title":"LivenessCheck.Error.FaceChanged","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceChanged","kind":"identifier"}],"abstract":[]},"doc://com.joinself.sdk/documentation/self_ios_sdk":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","url":"\/documentation\/self_ios_sdk","abstract":[],"title":"self_ios_sdk","kind":"symbol","role":"collection"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck":{"title":"LivenessCheck","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivenessCheck","kind":"identifier"}],"navigatorTitle":[{"text":"LivenessCheck","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/self_ios_sdk\/livenesscheck","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/title","value":"LivenessCheck","op":"replace"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/fragments","value":[{"kind":"identifier","text":"LivenessCheck"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/navigatorTitle","value":[{"kind":"identifier","text":"LivenessCheck"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}