{"hierarchy":{"paths":[["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SelfSDK"]]},"abstract":[{"type":"text","text":"New liveness check verification"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/self_ios_sdk\/selfsdk\/showliveness(account:showintroduction:isrequirecaptureselfie:autodismiss:isverificationrequired:onresult:)"]}],"metadata":{"extendedModule":"self_ios_sdk","role":"symbol","title":"showLiveness(account:showIntroduction:isRequireCaptureSelfie:autoDismiss:isVerificationRequired:onResult:)","modules":[{"name":"self_ios_sdk"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showLiveness","kind":"identifier"},{"text":"(","kind":"text"},{"text":"account","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Account","preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)Account","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"showIntroduction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isRequireCaptureSelfie","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"autoDismiss","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isVerificationRequired","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onResult","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", [","kind":"text"},{"text":"Credential","preciseIdentifier":"s:12self_ios_sdk10CredentialC","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"LivenessCheck","preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)LivenessCheck","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Error","preciseIdentifier":"s:12self_ios_sdk13LivenessCheckC5ErrorO","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"symbolKind":"method","externalID":"s:12self_ios_sdk7SelfSDKC12showLiveness7account0F12Introduction22isRequireCaptureSelfie11autoDismiss0J20VerificationRequired8onResultyAA7AccountC_S4by10Foundation4DataV_SayAA10CredentialCGAA0G5CheckC5ErrorOSgtcSgtFZ","roleHeading":"Type Method"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SelfSDK\/showLiveness(account:showIntroduction:isRequireCaptureSelfie:autoDismiss:isVerificationRequired:onResult:)"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showLiveness","kind":"identifier"},{"text":"(","kind":"text"},{"text":"account","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)Account","text":"Account","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"showIntroduction","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"text":"isRequireCaptureSelfie","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"text":"autoDismiss","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"text":"isVerificationRequired","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = true, ","kind":"text"},{"text":"onResult","kind":"externalParam"},{"text":": ((","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", [","kind":"text"},{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Credential","preciseIdentifier":"s:12self_ios_sdk10CredentialC","text":"Credential","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck","preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)LivenessCheck","text":"LivenessCheck","kind":"typeIdentifier"},{"text":".","kind":"text"},{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Error","preciseIdentifier":"s:12self_ios_sdk13LivenessCheckC5ErrorO","text":"Error","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")? = nil)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"An account uses to verify the liveness image","type":"text"}]}],"name":"account"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Show the induction screen or not","type":"text"}]}],"name":"showIntroduction"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Is required capture a selfie image to store for later usage"}]}],"name":"isRequireCaptureSelfie"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"autoDismiss the liveness check flow"}]}],"name":"autoDismiss"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Is required verification or not","type":"text"}]}],"name":"isVerificationRequired"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Completion of the flow that will contain "},{"code":"selfieImageData, credentials of liveness check image, error of the verification","type":"codeVoice"}]}],"name":"onResult"}],"kind":"parameters"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.joinself.sdk/documentation/self_ios_sdk/Credential":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Credential","kind":"identifier"}],"type":"topic","url":"\/documentation\/self_ios_sdk\/credential","abstract":[],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Credential","title":"Credential","kind":"symbol","navigatorTitle":[{"text":"Credential","kind":"identifier"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/Error":{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Error","type":"topic","role":"symbol","title":"LivenessCheck.Error","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/livenesscheck\/error"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck":{"title":"LivenessCheck","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivenessCheck","kind":"identifier"}],"navigatorTitle":[{"text":"LivenessCheck","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/self_ios_sdk\/livenesscheck","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account":{"abstract":[{"text":"Create Self Account","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Account","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/account","title":"Account","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","kind":"symbol","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","url":"\/documentation\/self_ios_sdk","abstract":[],"title":"self_ios_sdk","kind":"symbol","role":"collection"},"doc://com.joinself.sdk/documentation/self_ios_sdk/SelfSDK/showLiveness(account:showIntroduction:isRequireCaptureSelfie:autoDismiss:isVerificationRequired:onResult:)":{"abstract":[{"text":"New liveness check verification","type":"text"}],"url":"\/documentation\/self_ios_sdk\/selfsdk\/showliveness(account:showintroduction:isrequirecaptureselfie:autodismiss:isverificationrequired:onresult:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showLiveness"},{"kind":"text","text":"("},{"kind":"externalParam","text":"account"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)Account","kind":"typeIdentifier","text":"Account"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showIntroduction"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isRequireCaptureSelfie"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoDismiss"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isVerificationRequired"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onResult"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", ["},{"preciseIdentifier":"s:12self_ios_sdk10CredentialC","kind":"typeIdentifier","text":"Credential"},{"kind":"text","text":"], "},{"preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)LivenessCheck","kind":"typeIdentifier","text":"LivenessCheck"},{"kind":"text","text":"."},{"preciseIdentifier":"s:12self_ios_sdk13LivenessCheckC5ErrorO","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"title":"showLiveness(account:showIntroduction:isRequireCaptureSelfie:autoDismiss:isVerificationRequired:onResult:)","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SelfSDK\/showLiveness(account:showIntroduction:isRequireCaptureSelfie:autoDismiss:isVerificationRequired:onResult:)","kind":"symbol"},"doc://com.joinself.sdk/documentation/self_ios_sdk/SelfSDK":{"kind":"symbol","title":"SelfSDK","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SelfSDK","kind":"identifier"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SelfSDK","abstract":[],"role":"symbol","url":"\/documentation\/self_ios_sdk\/selfsdk","navigatorTitle":[{"text":"SelfSDK","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/title","value":"LivenessCheck"},{"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/fragments","value":[{"text":"LivenessCheck","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/navigatorTitle","value":[{"text":"LivenessCheck","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/title","value":"Account"},{"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/fragments","value":[{"text":"Account","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/navigatorTitle","value":[{"kind":"identifier","text":"Account"}]}]}]}