{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"RawRepresentable.hashValue"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/self_ios_sdk\/livenesscheck\/error\/hashvalue"]}],"identifier":{"url":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Error\/hashValue","interfaceLanguage":"swift"},"metadata":{"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::s:12self_ios_sdk13LivenessCheckC5ErrorO","extendedModule":"Swift","symbolKind":"property","roleHeading":"Instance Property","title":"hashValue","role":"symbol","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"modules":[{"relatedModules":["Swift"],"name":"self_ios_sdk"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Error","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Error\/RawRepresentable-Implementations"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/Error/hashValue":{"abstract":[],"url":"\/documentation\/self_ios_sdk\/livenesscheck\/error\/hashvalue","role":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Error\/hashValue","type":"topic","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"hashValue","kind":"symbol"},"doc://com.joinself.sdk/documentation/self_ios_sdk":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","url":"\/documentation\/self_ios_sdk","abstract":[],"title":"self_ios_sdk","kind":"symbol","role":"collection"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/Error/RawRepresentable-Implementations":{"type":"topic","title":"RawRepresentable Implementations","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Error\/RawRepresentable-Implementations","kind":"article","role":"collectionGroup","abstract":[],"url":"\/documentation\/self_ios_sdk\/livenesscheck\/error\/rawrepresentable-implementations"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/Error":{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Error","type":"topic","role":"symbol","title":"LivenessCheck.Error","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/livenesscheck\/error"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck":{"title":"LivenessCheck","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivenessCheck","kind":"identifier"}],"navigatorTitle":[{"text":"LivenessCheck","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/self_ios_sdk\/livenesscheck","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/title","value":"LivenessCheck"},{"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/fragments","value":[{"text":"LivenessCheck","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/navigatorTitle","value":[{"text":"LivenessCheck","kind":"identifier"}]}]}]}