# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'self-embedded-ios', :git => 'https://github.com/joinself/self-embedded-ios.git'

end
