{"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/captureOutput(_:didOutput:from:)"],"generated":true}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck"]]},"identifier":{"url":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"self_ios_sdk"}],"roleHeading":"API Collection","role":"collectionGroup","title":"AVCaptureVideoDataOutputSampleBufferDelegate Implementations"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/self_ios_sdk\/livenesscheck\/avcapturevideodataoutputsamplebufferdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/self_ios_sdk\/livenesscheck\/avcapturevideodataoutputsamplebufferdelegate-implementations"]}],"references":{"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck":{"title":"LivenessCheck","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivenessCheck","kind":"identifier"}],"navigatorTitle":[{"text":"LivenessCheck","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/self_ios_sdk\/livenesscheck","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","url":"\/documentation\/self_ios_sdk","abstract":[],"title":"self_ios_sdk","kind":"symbol","role":"collection"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/captureOutput(_:didOutput:from:)":{"url":"\/documentation\/self_ios_sdk\/livenesscheck\/captureoutput(_:didoutput:from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"captureOutput","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVCaptureOutput","preciseIdentifier":"c:objc(cs)AVCaptureOutput","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didOutput","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","kind":"typeIdentifier","text":"CMSampleBuffer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCaptureConnection","kind":"typeIdentifier","text":"AVCaptureConnection"},{"kind":"text","text":")"}],"title":"captureOutput(_:didOutput:from:)","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/captureOutput(_:didOutput:from:)","kind":"symbol","navigatorTitle":[{"text":"captureOutput:didOutputSampleBuffer:fromConnection:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/captureOutput(_:didOutput:from:)"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/title","op":"replace","value":"LivenessCheck"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/fragments","op":"replace","value":[{"kind":"identifier","text":"LivenessCheck"}]},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/navigatorTitle","op":"replace","value":[{"text":"LivenessCheck","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck~1captureOutput(_:didOutput:from:)\/title","op":"replace","value":"captureOutput:didOutputSampleBuffer:fromConnection:"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck~1captureOutput(_:didOutput:from:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"captureOutput:didOutputSampleBuffer:fromConnection:","kind":"identifier"}]}]}]}