{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","symbolKind":"method","externalID":"c:@CM@self_ios_sdk@objc(cs)LivenessCheck(im)captureOutput:didOutputSampleBuffer:fromConnection:","navigatorTitle":[{"text":"captureOutput:didOutputSampleBuffer:fromConnection:","kind":"identifier"}],"title":"captureOutput(_:didOutput:from:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureOutput","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVCaptureOutput","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureOutput"},{"text":", ","kind":"text"},{"text":"didOutput","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CMSampleBuffer","kind":"typeIdentifier","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"text":", ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVCaptureConnection","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureConnection"},{"text":")","kind":"text"}],"modules":[{"name":"self_ios_sdk"}],"roleHeading":"Instance Method","extendedModule":"self_ios_sdk"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"AVCaptureVideoDataOutputSampleBufferDelegate.captureOutput(_:didOutput:from:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureOutput","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"output","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AVCaptureOutput","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureOutput"},{"text":", ","kind":"text"},{"text":"didOutput","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sampleBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"connection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureConnection","preciseIdentifier":"c:objc(cs)AVCaptureConnection"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations"]]},"variants":[{"paths":["\/documentation\/self_ios_sdk\/livenesscheck\/captureoutput(_:didoutput:from:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/self_ios_sdk\/livenesscheck\/captureoutput(_:didoutput:from:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/captureOutput(_:didOutput:from:)"},"kind":"symbol","references":{"doc://com.joinself.sdk/documentation/self_ios_sdk":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","url":"\/documentation\/self_ios_sdk","abstract":[],"title":"self_ios_sdk","kind":"symbol","role":"collection"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck":{"title":"LivenessCheck","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivenessCheck","kind":"identifier"}],"navigatorTitle":[{"text":"LivenessCheck","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/self_ios_sdk\/livenesscheck","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations":{"abstract":[],"kind":"article","type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations","role":"collectionGroup","url":"\/documentation\/self_ios_sdk\/livenesscheck\/avcapturevideodataoutputsamplebufferdelegate-implementations","title":"AVCaptureVideoDataOutputSampleBufferDelegate Implementations"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/captureOutput(_:didOutput:from:)":{"url":"\/documentation\/self_ios_sdk\/livenesscheck\/captureoutput(_:didoutput:from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"captureOutput","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVCaptureOutput","preciseIdentifier":"c:objc(cs)AVCaptureOutput","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didOutput","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CMSampleBufferRef","kind":"typeIdentifier","text":"CMSampleBuffer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCaptureConnection","kind":"typeIdentifier","text":"AVCaptureConnection"},{"kind":"text","text":")"}],"title":"captureOutput(_:didOutput:from:)","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/captureOutput(_:didOutput:from:)","kind":"symbol","navigatorTitle":[{"text":"captureOutput:didOutputSampleBuffer:fromConnection:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"captureOutput:didOutputSampleBuffer:fromConnection:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"captureOutput:didOutputSampleBuffer:fromConnection:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"captureOutput:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVCaptureOutput","preciseIdentifier":"c:objc(cs)AVCaptureOutput","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"output","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didOutputSampleBuffer:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"opaqueCMSampleBuffer","preciseIdentifier":"c:@S@opaqueCMSampleBuffer","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sampleBuffer","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fromConnection:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVCaptureConnection","preciseIdentifier":"c:objc(cs)AVCaptureConnection","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"connection","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"LivenessCheck","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/title","op":"replace"},{"value":[{"kind":"identifier","text":"LivenessCheck"}],"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"LivenessCheck"}],"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/navigatorTitle","op":"replace"},{"value":"captureOutput:didOutputSampleBuffer:fromConnection:","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck~1captureOutput(_:didOutput:from:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"captureOutput:didOutputSampleBuffer:fromConnection:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck~1captureOutput(_:didOutput:from:)\/fragments","op":"replace"}]}]}