{"metadata":{"roleHeading":"Initializer","modules":[{"name":"self_ios_sdk"}],"externalID":"s:12self_ios_sdk13LivenessCheckC7accountAcA7AccountC_tcfc","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"account"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)Account","text":"Account"},{"kind":"text","text":")"}],"title":"init(account:)","symbolKind":"init"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/init(account:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"account","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Account","kind":"typeIdentifier","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)Account"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/self_ios_sdk\/livenesscheck\/init(account:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck"]]},"references":{"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck":{"title":"LivenessCheck","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivenessCheck","kind":"identifier"}],"navigatorTitle":[{"text":"LivenessCheck","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/self_ios_sdk\/livenesscheck","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","url":"\/documentation\/self_ios_sdk","abstract":[],"title":"self_ios_sdk","kind":"symbol","role":"collection"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account":{"abstract":[{"text":"Create Self Account","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Account","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/account","title":"Account","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","kind":"symbol","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/init(account:)":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/init(account:)","role":"symbol","url":"\/documentation\/self_ios_sdk\/livenesscheck\/init(account:)","kind":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"account"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)Account","kind":"typeIdentifier","text":"Account"},{"kind":"text","text":")"}],"title":"init(account:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"LivenessCheck","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/title"},{"op":"replace","value":[{"text":"LivenessCheck","kind":"identifier"}],"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"LivenessCheck"}],"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/navigatorTitle"},{"op":"replace","value":"Account","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/title"},{"op":"replace","value":[{"text":"Account","kind":"identifier"}],"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/fragments"},{"op":"replace","value":[{"text":"Account","kind":"identifier"}],"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}