{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"text":"Display onboarding flow to register a new account","type":"text"}],"metadata":{"modules":[{"name":"self_ios_sdk"}],"extendedModule":"self_ios_sdk","externalID":"s:12self_ios_sdk7SelfSDKC14showOnboarding7account8onFinishyAA7AccountC_ySbctFZ","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showOnboarding","kind":"identifier"},{"text":"(","kind":"text"},{"text":"account","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Account","kind":"typeIdentifier","preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)Account"},{"text":", ","kind":"text"},{"text":"onFinish","kind":"externalParam"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"roleHeading":"Type Method","role":"symbol","title":"showOnboarding(account:onFinish:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/self_ios_sdk\/selfsdk\/showonboarding(account:onfinish:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showOnboarding","kind":"identifier"},{"text":"(","kind":"text"},{"text":"account","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Account","kind":"typeIdentifier","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)Account"},{"text":", ","kind":"text"},{"text":"onFinish","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" ((","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":"))","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"account","content":[{"inlineContent":[{"type":"text","text":"An account uses to register to self network"}],"type":"paragraph"}]},{"name":"onFinish","content":[{"type":"paragraph","inlineContent":[{"text":"Completion of the flow with status of result","type":"text"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SelfSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SelfSDK\/showOnboarding(account:onFinish:)"},"kind":"symbol","references":{"doc://com.joinself.sdk/documentation/self_ios_sdk/SelfSDK/showOnboarding(account:onFinish:)":{"url":"\/documentation\/self_ios_sdk\/selfsdk\/showonboarding(account:onfinish:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showOnboarding"},{"kind":"text","text":"("},{"kind":"externalParam","text":"account"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)Account","text":"Account"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onFinish"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":"))"}],"kind":"symbol","title":"showOnboarding(account:onFinish:)","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SelfSDK\/showOnboarding(account:onFinish:)","abstract":[{"type":"text","text":"Display onboarding flow to register a new account"}],"role":"symbol","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account":{"abstract":[{"text":"Create Self Account","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Account","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/account","title":"Account","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","kind":"symbol","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","url":"\/documentation\/self_ios_sdk","abstract":[],"title":"self_ios_sdk","kind":"symbol","role":"collection"},"doc://com.joinself.sdk/documentation/self_ios_sdk/SelfSDK":{"kind":"symbol","title":"SelfSDK","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SelfSDK","kind":"identifier"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SelfSDK","abstract":[],"role":"symbol","url":"\/documentation\/self_ios_sdk\/selfsdk","navigatorTitle":[{"text":"SelfSDK","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/title","value":"Account"},{"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/fragments","value":[{"kind":"identifier","text":"Account"}]},{"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/navigatorTitle","value":[{"text":"Account","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}