{"identifier":{"url":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SelfSDK\/startLiveness(account:currentVC:isVerificationRequired:dismissal:isRequireCaptureSelfieImage:onResult:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startLiveness","kind":"identifier"},{"text":"(","kind":"text"},{"text":"account","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Account","kind":"typeIdentifier","preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)Account"},{"text":"?, ","kind":"text"},{"text":"currentVC","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?, ","kind":"text"},{"text":"isVerificationRequired","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"dismissal","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"isRequireCaptureSelfieImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"onResult","kind":"externalParam"},{"text":": ((","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", [","kind":"text"},{"text":"Credential","kind":"typeIdentifier","preciseIdentifier":"s:12self_ios_sdk10CredentialC"},{"text":"], ","kind":"text"},{"text":"LivenessCheck","kind":"typeIdentifier","preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)LivenessCheck"},{"text":".","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:12self_ios_sdk13LivenessCheckC5ErrorO"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"extendedModule":"self_ios_sdk","modules":[{"name":"self_ios_sdk"}],"symbolKind":"method","role":"symbol","roleHeading":"Type Method","externalID":"s:12self_ios_sdk7SelfSDKC13startLiveness7account9currentVC22isVerificationRequired9dismissal0K25RequireCaptureSelfieImage8onResultyAA7AccountCSg_So16UIViewControllerCSgS3by10Foundation4DataV_SayAA10CredentialCGAA0G5CheckC5ErrorOSgtcSgtFZ","title":"startLiveness(account:currentVC:isVerificationRequired:dismissal:isRequireCaptureSelfieImage:onResult:)"},"hierarchy":{"paths":[["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SelfSDK"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startLiveness"},{"kind":"text","text":"("},{"kind":"externalParam","text":"account"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Account","preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)Account","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"currentVC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"isVerificationRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"dismissal"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"isRequireCaptureSelfieImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = true, "},{"kind":"externalParam","text":"onResult"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", ["},{"kind":"typeIdentifier","text":"Credential","preciseIdentifier":"s:12self_ios_sdk10CredentialC","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Credential"},{"kind":"text","text":"], "},{"kind":"typeIdentifier","text":"LivenessCheck","preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)LivenessCheck","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:12self_ios_sdk13LivenessCheckC5ErrorO","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Error"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")? = nil)"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/self_ios_sdk\/selfsdk\/startliveness(account:currentvc:isverificationrequired:dismissal:isrequirecaptureselfieimage:onresult:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.joinself.sdk/documentation/self_ios_sdk/Account":{"abstract":[{"text":"Create Self Account","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Account","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/account","title":"Account","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","kind":"symbol","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/Error":{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Error","type":"topic","role":"symbol","title":"LivenessCheck.Error","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/livenesscheck\/error"},"doc://com.joinself.sdk/documentation/self_ios_sdk/SelfSDK":{"kind":"symbol","title":"SelfSDK","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SelfSDK","kind":"identifier"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SelfSDK","abstract":[],"role":"symbol","url":"\/documentation\/self_ios_sdk\/selfsdk","navigatorTitle":[{"text":"SelfSDK","kind":"identifier"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/SelfSDK/startLiveness(account:currentVC:isVerificationRequired:dismissal:isRequireCaptureSelfieImage:onResult:)":{"url":"\/documentation\/self_ios_sdk\/selfsdk\/startliveness(account:currentvc:isverificationrequired:dismissal:isrequirecaptureselfieimage:onresult:)","title":"startLiveness(account:currentVC:isVerificationRequired:dismissal:isRequireCaptureSelfieImage:onResult:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startLiveness"},{"kind":"text","text":"("},{"kind":"externalParam","text":"account"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)Account","kind":"typeIdentifier","text":"Account"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"currentVC"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isVerificationRequired"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dismissal"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isRequireCaptureSelfieImage"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onResult"},{"kind":"text","text":": (("},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", ["},{"preciseIdentifier":"s:12self_ios_sdk10CredentialC","kind":"typeIdentifier","text":"Credential"},{"kind":"text","text":"], "},{"preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)LivenessCheck","kind":"typeIdentifier","text":"LivenessCheck"},{"kind":"text","text":"."},{"preciseIdentifier":"s:12self_ios_sdk13LivenessCheckC5ErrorO","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?)"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SelfSDK\/startLiveness(account:currentVC:isVerificationRequired:dismissal:isRequireCaptureSelfieImage:onResult:)","abstract":[]},"doc://com.joinself.sdk/documentation/self_ios_sdk/Credential":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Credential","kind":"identifier"}],"type":"topic","url":"\/documentation\/self_ios_sdk\/credential","abstract":[],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Credential","title":"Credential","kind":"symbol","navigatorTitle":[{"text":"Credential","kind":"identifier"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck":{"title":"LivenessCheck","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivenessCheck","kind":"identifier"}],"navigatorTitle":[{"text":"LivenessCheck","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/self_ios_sdk\/livenesscheck","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","url":"\/documentation\/self_ios_sdk","abstract":[],"title":"self_ios_sdk","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/title","value":"Account"},{"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/fragments","value":[{"kind":"identifier","text":"Account"}]},{"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/navigatorTitle","value":[{"kind":"identifier","text":"Account"}]},{"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/title","value":"LivenessCheck"},{"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/fragments","value":[{"text":"LivenessCheck","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/navigatorTitle","value":[{"kind":"identifier","text":"LivenessCheck"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}