{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/CLLocationManagerDelegate-Implementations"},"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"self_ios_sdk"}],"title":"CLLocationManagerDelegate Implementations"},"sections":[],"variants":[{"paths":["\/documentation\/self_ios_sdk\/account\/cllocationmanagerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/self_ios_sdk\/account\/cllocationmanagerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/locationManager(_:didFailWithError:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/locationManager(_:didUpdateLocations:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/locationManagerDidChangeAuthorization(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"hierarchy":{"paths":[["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account"]]},"references":{"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/locationManager(_:didFailWithError:)":{"kind":"symbol","type":"topic","title":"locationManager(_:didFailWithError:)","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/locationManager(_:didFailWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"locationManager:didFailWithError:"}],"url":"\/documentation\/self_ios_sdk\/account\/locationmanager(_:didfailwitherror:)","role":"symbol","abstract":[]},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/locationManager(_:didUpdateLocations:)":{"title":"locationManager(_:didUpdateLocations:)","abstract":[],"navigatorTitle":[{"text":"locationManager:didUpdateLocations:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/locationManager(_:didUpdateLocations:)","type":"topic","role":"symbol","url":"\/documentation\/self_ios_sdk\/account\/locationmanager(_:didupdatelocations:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locationManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CLLocationManager","text":"CLLocationManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateLocations","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)CLLocation","text":"CLLocation","kind":"typeIdentifier"},{"text":"])","kind":"text"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","url":"\/documentation\/self_ios_sdk","abstract":[],"title":"self_ios_sdk","kind":"symbol","role":"collection"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/locationManagerDidChangeAuthorization(_:)":{"navigatorTitle":[{"text":"locationManagerDidChangeAuthorization:","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/self_ios_sdk\/account\/locationmanagerdidchangeauthorization(_:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locationManagerDidChangeAuthorization","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CLLocationManager","text":"CLLocationManager","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/locationManagerDidChangeAuthorization(_:)","title":"locationManagerDidChangeAuthorization(_:)"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account":{"abstract":[{"text":"Create Self Account","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Account","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/account","title":"Account","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/locationManager(_:didFailWithError:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/locationManager(_:didUpdateLocations:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/locationManagerDidChangeAuthorization(_:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"locationManager:didFailWithError:","op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account~1locationManager(_:didFailWithError:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"locationManager:didFailWithError:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account~1locationManager(_:didFailWithError:)\/fragments"},{"value":"locationManager:didUpdateLocations:","op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account~1locationManager(_:didUpdateLocations:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManager:didUpdateLocations:"}],"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account~1locationManager(_:didUpdateLocations:)\/fragments"},{"value":"locationManagerDidChangeAuthorization:","op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account~1locationManagerDidChangeAuthorization(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManagerDidChangeAuthorization:"}],"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account~1locationManagerDidChangeAuthorization(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/title","op":"replace","value":"Account"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/fragments","op":"replace","value":[{"text":"Account","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/navigatorTitle","op":"replace","value":[{"text":"Account","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}