{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decryptNotification"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"payload"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Notification","preciseIdentifier":"s:12self_ios_sdk12NotificationC","kind":"typeIdentifier","text":"Notification"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decryptNotification","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forAddress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"payload","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"Notification","kind":"typeIdentifier","preciseIdentifier":"s:12self_ios_sdk12NotificationC"},{"text":"?","kind":"text"}],"modules":[{"name":"self_ios_sdk"}],"externalID":"s:12self_ios_sdk7AccountC19decryptNotification10forAddress7payloadAA0F0CSgSS_SStF","title":"decryptNotification(forAddress:payload:)","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/decryptNotification(forAddress:payload:)"},"hierarchy":{"paths":[["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/self_ios_sdk\/account\/decryptnotification(foraddress:payload:)"]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.joinself.sdk/documentation/self_ios_sdk/Account":{"abstract":[{"text":"Create Self Account","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Account","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/account","title":"Account","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","kind":"symbol","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Notification":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Notification"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Notification","url":"\/documentation\/self_ios_sdk\/notification","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Notification"}],"abstract":[],"title":"Notification"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/decryptNotification(forAddress:payload:)":{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/decryptNotification(forAddress:payload:)","title":"decryptNotification(forAddress:payload:)","url":"\/documentation\/self_ios_sdk\/account\/decryptnotification(foraddress:payload:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decryptNotification"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"payload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:12self_ios_sdk12NotificationC","text":"Notification"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol"},"doc://com.joinself.sdk/documentation/self_ios_sdk":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","url":"\/documentation\/self_ios_sdk","abstract":[],"title":"self_ios_sdk","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/title","op":"replace","value":"Account"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/fragments","op":"replace","value":[{"kind":"identifier","text":"Account"}]},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"Account"}]}]}]}