{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CLLocationManagerDelegate.locationManager(_:didUpdateLocations:)"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/self_ios_sdk\/account\/locationmanager(_:didupdatelocations:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/self_ios_sdk\/account\/locationmanager(_:didupdatelocations:)"]}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didUpdateLocations"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"CLLocation","preciseIdentifier":"c:objc(cs)CLLocation"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"locationManager:didUpdateLocations:"}],"externalID":"c:@CM@self_ios_sdk@objc(cs)Account(im)locationManager:didUpdateLocations:","extendedModule":"self_ios_sdk","role":"symbol","title":"locationManager(_:didUpdateLocations:)","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"self_ios_sdk"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locationManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"manager","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CLLocationManager","text":"CLLocationManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateLocations","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"locations","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"CLLocation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CLLocation"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/CLLocationManagerDelegate-Implementations"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/locationManager(_:didUpdateLocations:)","interfaceLanguage":"swift"},"references":{"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/locationManager(_:didUpdateLocations:)":{"title":"locationManager(_:didUpdateLocations:)","abstract":[],"navigatorTitle":[{"text":"locationManager:didUpdateLocations:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/locationManager(_:didUpdateLocations:)","type":"topic","role":"symbol","url":"\/documentation\/self_ios_sdk\/account\/locationmanager(_:didupdatelocations:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locationManager","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CLLocationManager","text":"CLLocationManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didUpdateLocations","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)CLLocation","text":"CLLocation","kind":"typeIdentifier"},{"text":"])","kind":"text"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/CLLocationManagerDelegate-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/self_ios_sdk\/account\/cllocationmanagerdelegate-implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/CLLocationManagerDelegate-Implementations","title":"CLLocationManagerDelegate Implementations"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account":{"abstract":[{"text":"Create Self Account","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Account","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/account","title":"Account","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","kind":"symbol","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","url":"\/documentation\/self_ios_sdk","abstract":[],"title":"self_ios_sdk","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"locationManager:didUpdateLocations:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManager:didUpdateLocations:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"locationManager:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CLLocationManager","text":"CLLocationManager","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"manager","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didUpdateLocations:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<CLLocation *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"locations","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account~1locationManager(_:didUpdateLocations:)\/title","op":"replace","value":"locationManager:didUpdateLocations:"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account~1locationManager(_:didUpdateLocations:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManager:didUpdateLocations:"}]},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/title","op":"replace","value":"Account"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/fragments","op":"replace","value":[{"text":"Account","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/navigatorTitle","op":"replace","value":[{"text":"Account","kind":"identifier"}]}]}]}