{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@CM@self_ios_sdk@objc(cs)Account(im)locationManager:didFailWithError:","modules":[{"name":"self_ios_sdk"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"extendedModule":"self_ios_sdk","navigatorTitle":[{"kind":"identifier","text":"locationManager:didFailWithError:"}],"role":"symbol","title":"locationManager(_:didFailWithError:)"},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"CLLocationManagerDelegate.locationManager(_:didFailWithError:)","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/locationManager(_:didFailWithError:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/self_ios_sdk\/account\/locationmanager(_:didfailwitherror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/self_ios_sdk\/account\/locationmanager(_:didfailwitherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/CLLocationManagerDelegate-Implementations"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"manager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CLLocationManager","text":"CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailWithError"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.joinself.sdk/documentation/self_ios_sdk/Account":{"abstract":[{"text":"Create Self Account","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Account","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/account","title":"Account","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","kind":"symbol","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","url":"\/documentation\/self_ios_sdk","abstract":[],"title":"self_ios_sdk","kind":"symbol","role":"collection"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/locationManager(_:didFailWithError:)":{"kind":"symbol","type":"topic","title":"locationManager(_:didFailWithError:)","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/locationManager(_:didFailWithError:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailWithError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"locationManager:didFailWithError:"}],"url":"\/documentation\/self_ios_sdk\/account\/locationmanager(_:didfailwitherror:)","role":"symbol","abstract":[]},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/CLLocationManagerDelegate-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/self_ios_sdk\/account\/cllocationmanagerdelegate-implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/CLLocationManagerDelegate-Implementations","title":"CLLocationManagerDelegate Implementations"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"locationManager:didFailWithError:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManager:didFailWithError:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"locationManager:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"manager"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailWithError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"Account","op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/title"},{"value":[{"text":"Account","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/fragments"},{"value":[{"kind":"identifier","text":"Account"}],"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/navigatorTitle"},{"value":"locationManager:didFailWithError:","op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account~1locationManager(_:didFailWithError:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"locationManager:didFailWithError:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account~1locationManager(_:didFailWithError:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}