{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Framework","title":"self_ios_sdk","externalID":"self_ios_sdk","role":"collection","modules":[{"name":"self_ios_sdk"}],"symbolKind":"module"},"sections":[],"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Attachment","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/ChatMessage","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Claim","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Credential","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/CredentialRequest","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/CredentialResponse","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/DataObject","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Document","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/KeyValue","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/NewLivenessCheckViewModel","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Notification","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Receipt","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SecurityCodeRequest","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SecurityCodeResponse","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SelfSDK","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/ShareResources","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Signable","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SigningRequest","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SigningResponse","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/VerificationRequest","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/VerificationResponse"],"anchor":"Classes","generated":true},{"title":"Protocols","identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Message"],"anchor":"Protocols","generated":true},{"title":"Structures","identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Constants","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/CredentialType","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/CredentialsByType","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/DiscoveryData","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/DocumentFlow","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/EmailFlow","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheckFlow","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/NewLivenessCheckFlow","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/QRCodeReaderView","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/ez"],"anchor":"Structures","generated":true},{"title":"Enumerations","identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/ComparisonOperator","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/ContentSummaryType","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Environment","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/ResponseStatus"],"anchor":"Enumerations","generated":true},{"title":"Extended Modules","identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Foundation","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/UIKit"],"anchor":"Extended-Modules","generated":true}],"variants":[{"paths":["\/documentation\/self_ios_sdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/self_ios_sdk"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[[]]},"identifier":{"url":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","interfaceLanguage":"swift"},"references":{"doc://com.joinself.sdk/documentation/self_ios_sdk/Receipt":{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Receipt","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Receipt"}],"kind":"symbol","type":"topic","title":"Receipt","url":"\/documentation\/self_ios_sdk\/receipt","navigatorTitle":[{"kind":"identifier","text":"Receipt"}],"abstract":[]},"doc://com.joinself.sdk/documentation/self_ios_sdk/EmailFlow":{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/EmailFlow","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EmailFlow","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EmailFlow"}],"title":"EmailFlow","abstract":[],"url":"\/documentation\/self_ios_sdk\/emailflow"},"doc://com.joinself.sdk/documentation/self_ios_sdk/VerificationRequest":{"title":"VerificationRequest","kind":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/VerificationRequest","url":"\/documentation\/self_ios_sdk\/verificationrequest","navigatorTitle":[{"kind":"identifier","text":"VerificationRequest"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VerificationRequest"}],"type":"topic","abstract":[]},"doc://com.joinself.sdk/documentation/self_ios_sdk/CredentialRequest":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CredentialRequest","kind":"identifier"}],"navigatorTitle":[{"text":"CredentialRequest","kind":"identifier"}],"title":"CredentialRequest","abstract":[{"type":"text","text":"requests attested facts from an identity"}],"role":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/CredentialRequest","url":"\/documentation\/self_ios_sdk\/credentialrequest"},"doc://com.joinself.sdk/documentation/self_ios_sdk/VerificationResponse":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VerificationResponse"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/VerificationResponse","navigatorTitle":[{"kind":"identifier","text":"VerificationResponse"}],"url":"\/documentation\/self_ios_sdk\/verificationresponse","abstract":[],"title":"VerificationResponse","kind":"symbol","type":"topic","role":"symbol"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Foundation":{"title":"Foundation","kind":"symbol","role":"collection","abstract":[],"type":"topic","url":"\/documentation\/self_ios_sdk\/foundation","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Foundation"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck":{"title":"LivenessCheck","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivenessCheck","kind":"identifier"}],"navigatorTitle":[{"text":"LivenessCheck","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/self_ios_sdk\/livenesscheck","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Message":{"abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Message"}],"kind":"symbol","title":"Message","url":"\/documentation\/self_ios_sdk\/message","role":"symbol","type":"topic","navigatorTitle":[{"text":"Message","kind":"identifier"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Message"},"doc://com.joinself.sdk/documentation/self_ios_sdk/ez":{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/ez","title":"ez","type":"topic","role":"symbol","url":"\/documentation\/self_ios_sdk\/ez","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ez"}],"navigatorTitle":[{"kind":"identifier","text":"ez"}],"abstract":[]},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account":{"abstract":[{"text":"Create Self Account","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Account","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/account","title":"Account","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","kind":"symbol","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Claim":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Claim"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Claim"}],"title":"Claim","kind":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Claim","type":"topic","url":"\/documentation\/self_ios_sdk\/claim","role":"symbol"},"doc://com.joinself.sdk/documentation/self_ios_sdk/KeyValue":{"type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"KeyValue","kind":"identifier"}],"navigatorTitle":[{"text":"KeyValue","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/keyvalue","title":"KeyValue","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/KeyValue"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Environment":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"url":"\/documentation\/self_ios_sdk\/environment","kind":"symbol","abstract":[],"title":"Environment","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Environment"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Environment"},"doc://com.joinself.sdk/documentation/self_ios_sdk/SigningRequest":{"kind":"symbol","type":"topic","role":"symbol","title":"SigningRequest","abstract":[{"text":"requests attested facts from an identity","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SigningRequest","kind":"identifier"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SigningRequest","navigatorTitle":[{"text":"SigningRequest","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/signingrequest"},"doc://com.joinself.sdk/documentation/self_ios_sdk/ComparisonOperator":{"role":"symbol","kind":"symbol","title":"ComparisonOperator","abstract":[],"url":"\/documentation\/self_ios_sdk\/comparisonoperator","type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/ComparisonOperator","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ComparisonOperator","kind":"identifier"}],"navigatorTitle":[{"text":"ComparisonOperator","kind":"identifier"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/QRCodeReaderView":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/QRCodeReaderView","title":"QRCodeReaderView","role":"symbol","url":"\/documentation\/self_ios_sdk\/qrcodereaderview","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"QRCodeReaderView"}],"navigatorTitle":[{"kind":"identifier","text":"QRCodeReaderView"}],"kind":"symbol"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Credential":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Credential","kind":"identifier"}],"type":"topic","url":"\/documentation\/self_ios_sdk\/credential","abstract":[],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Credential","title":"Credential","kind":"symbol","navigatorTitle":[{"text":"Credential","kind":"identifier"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/ResponseStatus":{"url":"\/documentation\/self_ios_sdk\/responsestatus","type":"topic","navigatorTitle":[{"text":"ResponseStatus","kind":"identifier"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/ResponseStatus","abstract":[],"title":"ResponseStatus","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResponseStatus","kind":"identifier"}],"kind":"symbol"},"doc://com.joinself.sdk/documentation/self_ios_sdk/ContentSummaryType":{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/ContentSummaryType","kind":"symbol","title":"ContentSummaryType","url":"\/documentation\/self_ios_sdk\/contentsummarytype","type":"topic","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContentSummaryType","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ContentSummaryType","kind":"identifier"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheckFlow":{"navigatorTitle":[{"text":"LivenessCheckFlow","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheckFlow","url":"\/documentation\/self_ios_sdk\/livenesscheckflow","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivenessCheckFlow","kind":"identifier"}],"type":"topic","title":"LivenessCheckFlow"},"doc://com.joinself.sdk/documentation/self_ios_sdk/self_ios_sdkVersionNumber":{"type":"topic","abstract":[{"type":"text","text":"Project version number for self_ios_sdk."}],"title":"self_ios_sdkVersionNumber","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/self_ios_sdkVersionNumber","role":"symbol","kind":"symbol","url":"\/documentation\/self_ios_sdk\/self_ios_sdkversionnumber","fragments":[{"kind":"identifier","text":"self_ios_sdkVersionNumber"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/DataObject":{"role":"symbol","navigatorTitle":[{"text":"DataObject","kind":"identifier"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/DataObject","abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataObject","kind":"identifier"}],"title":"DataObject","kind":"symbol","url":"\/documentation\/self_ios_sdk\/dataobject"},"doc://com.joinself.sdk/documentation/self_ios_sdk/UIKit":{"abstract":[],"url":"\/documentation\/self_ios_sdk\/uikit","title":"UIKit","type":"topic","role":"collection","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/UIKit","kind":"symbol"},"doc://com.joinself.sdk/documentation/self_ios_sdk/SigningResponse":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SigningResponse"}],"kind":"symbol","url":"\/documentation\/self_ios_sdk\/signingresponse","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SigningResponse","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SigningResponse"}],"title":"SigningResponse","abstract":[]},"doc://com.joinself.sdk/documentation/self_ios_sdk/Signable":{"url":"\/documentation\/self_ios_sdk\/signable","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Signable","kind":"identifier"}],"navigatorTitle":[{"text":"Signable","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Signable","abstract":[],"title":"Signable"},"doc://com.joinself.sdk/documentation/self_ios_sdk/SecurityCodeResponse":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/self_ios_sdk\/securitycoderesponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SecurityCodeResponse"}],"navigatorTitle":[{"kind":"identifier","text":"SecurityCodeResponse"}],"title":"SecurityCodeResponse","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SecurityCodeResponse","abstract":[]},"doc://com.joinself.sdk/documentation/self_ios_sdk/self_ios_sdkVersionString":{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/self_ios_sdkVersionString","title":"self_ios_sdkVersionString","role":"symbol","kind":"symbol","fragments":[{"text":"self_ios_sdkVersionString","kind":"identifier"}],"type":"topic","url":"\/documentation\/self_ios_sdk\/self_ios_sdkversionstring","abstract":[{"type":"text","text":"Project version string for self_ios_sdk."}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/Constants":{"role":"symbol","title":"Constants","type":"topic","abstract":[],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Constants","url":"\/documentation\/self_ios_sdk\/constants","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Constants"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Constants","kind":"identifier"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/SecurityCodeRequest":{"title":"SecurityCodeRequest","role":"symbol","kind":"symbol","url":"\/documentation\/self_ios_sdk\/securitycoderequest","navigatorTitle":[{"text":"SecurityCodeRequest","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SecurityCodeRequest","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SecurityCodeRequest","kind":"identifier"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/Attachment":{"navigatorTitle":[{"text":"Attachment","kind":"identifier"}],"role":"symbol","abstract":[],"title":"Attachment","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Attachment","type":"topic","url":"\/documentation\/self_ios_sdk\/attachment","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Attachment","kind":"identifier"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/CredentialResponse":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/CredentialResponse","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CredentialResponse","kind":"identifier"}],"navigatorTitle":[{"text":"CredentialResponse","kind":"identifier"}],"title":"CredentialResponse","role":"symbol","url":"\/documentation\/self_ios_sdk\/credentialresponse"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Notification":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Notification"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Notification","url":"\/documentation\/self_ios_sdk\/notification","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Notification"}],"abstract":[],"title":"Notification"},"doc://com.joinself.sdk/documentation/self_ios_sdk/NewLivenessCheckViewModel":{"role":"symbol","title":"NewLivenessCheckViewModel","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NewLivenessCheckViewModel"}],"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/NewLivenessCheckViewModel","navigatorTitle":[{"kind":"identifier","text":"NewLivenessCheckViewModel"}],"url":"\/documentation\/self_ios_sdk\/newlivenesscheckviewmodel"},"doc://com.joinself.sdk/documentation/self_ios_sdk/ChatMessage":{"title":"ChatMessage","type":"topic","url":"\/documentation\/self_ios_sdk\/chatmessage","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatMessage","kind":"identifier"}],"navigatorTitle":[{"text":"ChatMessage","kind":"identifier"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/ChatMessage","role":"symbol"},"doc://com.joinself.sdk/documentation/self_ios_sdk":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","url":"\/documentation\/self_ios_sdk","abstract":[],"title":"self_ios_sdk","kind":"symbol","role":"collection"},"doc://com.joinself.sdk/documentation/self_ios_sdk/DiscoveryData":{"kind":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/DiscoveryData","url":"\/documentation\/self_ios_sdk\/discoverydata","title":"DiscoveryData","role":"symbol","navigatorTitle":[{"text":"DiscoveryData","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DiscoveryData","kind":"identifier"}],"type":"topic","abstract":[{"text":"Represents discovery data extracted from a QR code.","type":"text"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/CredentialsByType":{"abstract":[{"text":"Represents a collection of credentials grouped by their types.","type":"text"}],"type":"topic","title":"CredentialsByType","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CredentialsByType","kind":"identifier"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/CredentialsByType","url":"\/documentation\/self_ios_sdk\/credentialsbytype","role":"symbol","navigatorTitle":[{"text":"CredentialsByType","kind":"identifier"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/NewLivenessCheckFlow":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NewLivenessCheckFlow","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/self_ios_sdk\/newlivenesscheckflow","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/NewLivenessCheckFlow","title":"NewLivenessCheckFlow","abstract":[],"role":"symbol","navigatorTitle":[{"text":"NewLivenessCheckFlow","kind":"identifier"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/Document":{"url":"\/documentation\/self_ios_sdk\/document","role":"symbol","title":"Document","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Document","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Document"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Document"}],"abstract":[]},"doc://com.joinself.sdk/documentation/self_ios_sdk/CredentialType":{"url":"\/documentation\/self_ios_sdk\/credentialtype","role":"symbol","navigatorTitle":[{"text":"CredentialType","kind":"identifier"}],"title":"CredentialType","type":"topic","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CredentialType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/CredentialType"},"doc://com.joinself.sdk/documentation/self_ios_sdk/SelfSDK":{"kind":"symbol","title":"SelfSDK","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SelfSDK","kind":"identifier"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/SelfSDK","abstract":[],"role":"symbol","url":"\/documentation\/self_ios_sdk\/selfsdk","navigatorTitle":[{"text":"SelfSDK","kind":"identifier"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/DocumentFlow":{"url":"\/documentation\/self_ios_sdk\/documentflow","abstract":[],"role":"symbol","navigatorTitle":[{"text":"DocumentFlow","kind":"identifier"}],"title":"DocumentFlow","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentFlow","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/DocumentFlow"},"doc://com.joinself.sdk/documentation/self_ios_sdk/ShareResources":{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/ShareResources","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShareResources"}],"role":"symbol","type":"topic","title":"ShareResources","navigatorTitle":[{"kind":"identifier","text":"ShareResources"}],"url":"\/documentation\/self_ios_sdk\/shareresources"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck"],"anchor":"Classes","title":"Classes"},{"generated":true,"identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/self_ios_sdkVersionNumber","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/self_ios_sdkVersionString"],"anchor":"Variables","title":"Variables"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/title","value":"LivenessCheck","op":"replace"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/fragments","value":[{"kind":"identifier","text":"LivenessCheck"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/navigatorTitle","value":[{"kind":"identifier","text":"LivenessCheck"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/title","value":"Account","op":"replace"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/fragments","value":[{"kind":"identifier","text":"Account"}],"op":"replace"},{"value":[{"text":"Account","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}