{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backup","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Self_backup file URL"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/self_ios_sdk\/account\/backup()"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/backup()"},"kind":"symbol","metadata":{"modules":[{"name":"self_ios_sdk"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backup","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"backup()","role":"symbol","externalID":"s:12self_ios_sdk7AccountC6backup10Foundation3URLVSgyYaF","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account"]]},"abstract":[{"type":"text","text":"backup data in PDS into a "},{"code":".self_backup","type":"codeVoice"},{"type":"text","text":" zip file"}],"references":{"doc://com.joinself.sdk/documentation/self_ios_sdk":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","url":"\/documentation\/self_ios_sdk","abstract":[],"title":"self_ios_sdk","kind":"symbol","role":"collection"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/backup()":{"title":"backup()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backup","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/backup()","url":"\/documentation\/self_ios_sdk\/account\/backup()","kind":"symbol","abstract":[{"text":"backup data in PDS into a ","type":"text"},{"code":".self_backup","type":"codeVoice"},{"text":" zip file","type":"text"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account":{"abstract":[{"text":"Create Self Account","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Account","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/account","title":"Account","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"Account","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Account"}],"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Account"}],"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}