{"variants":[{"paths":["\/documentation\/self_ios_sdk\/account\/location()"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"externalID":"s:12self_ios_sdk7AccountC8locationSayAA10CredentialCGyYaKF","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"location"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ["},{"kind":"typeIdentifier","text":"Credential","preciseIdentifier":"s:12self_ios_sdk10CredentialC"},{"kind":"text","text":"]"}],"title":"location()","modules":[{"name":"self_ios_sdk"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/location()"},"abstract":[{"type":"text","text":"request location and wait for the result"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"location"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ["},{"preciseIdentifier":"s:12self_ios_sdk10CredentialC","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Credential","kind":"typeIdentifier","text":"Credential"},{"kind":"text","text":"]"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The location attestation signed by self_verification"}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"SelfError.PermissionRequried"},{"type":"text","text":" location permissions"}],"type":"paragraph"}],"style":"note","type":"aside","name":"Throws"}]}],"hierarchy":{"paths":[["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account"]]},"references":{"doc://com.joinself.sdk/documentation/self_ios_sdk":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","url":"\/documentation\/self_ios_sdk","abstract":[],"title":"self_ios_sdk","kind":"symbol","role":"collection"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Credential":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Credential","kind":"identifier"}],"type":"topic","url":"\/documentation\/self_ios_sdk\/credential","abstract":[],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Credential","title":"Credential","kind":"symbol","navigatorTitle":[{"text":"Credential","kind":"identifier"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account":{"abstract":[{"text":"Create Self Account","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Account","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/account","title":"Account","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","kind":"symbol","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/location()":{"title":"location()","url":"\/documentation\/self_ios_sdk\/account\/location()","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"location","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"Credential","kind":"typeIdentifier","preciseIdentifier":"s:12self_ios_sdk10CredentialC"},{"text":"]","kind":"text"}],"abstract":[{"text":"request location and wait for the result","type":"text"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/location()","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/title","value":"Account","op":"replace"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/fragments","value":[{"text":"Account","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/navigatorTitle","value":[{"kind":"identifier","text":"Account"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}