{"identifier":{"url":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/locationManagerDidChangeAuthorization(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/self_ios_sdk\/account\/locationmanagerdidchangeauthorization(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/self_ios_sdk\/account\/locationmanagerdidchangeauthorization(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"CLLocationManagerDelegate.locationManagerDidChangeAuthorization(_:)","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/CLLocationManagerDelegate-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManagerDidChangeAuthorization"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"manager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CLLocationManager","text":"CLLocationManager"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"locationManagerDidChangeAuthorization:"}],"externalID":"c:@CM@self_ios_sdk@objc(cs)Account(im)locationManagerDidChangeAuthorization:","roleHeading":"Instance Method","role":"symbol","extendedModule":"self_ios_sdk","modules":[{"name":"self_ios_sdk"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"locationManagerDidChangeAuthorization"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CLLocationManager","kind":"typeIdentifier","text":"CLLocationManager"},{"kind":"text","text":")"}],"title":"locationManagerDidChangeAuthorization(_:)"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.joinself.sdk/documentation/self_ios_sdk/Account":{"abstract":[{"text":"Create Self Account","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Account","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/account","title":"Account","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","kind":"symbol","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/locationManagerDidChangeAuthorization(_:)":{"navigatorTitle":[{"text":"locationManagerDidChangeAuthorization:","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/self_ios_sdk\/account\/locationmanagerdidchangeauthorization(_:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"locationManagerDidChangeAuthorization","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CLLocationManager","text":"CLLocationManager","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/locationManagerDidChangeAuthorization(_:)","title":"locationManagerDidChangeAuthorization(_:)"},"doc://com.joinself.sdk/documentation/self_ios_sdk":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","url":"\/documentation\/self_ios_sdk","abstract":[],"title":"self_ios_sdk","kind":"symbol","role":"collection"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/CLLocationManagerDelegate-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/self_ios_sdk\/account\/cllocationmanagerdelegate-implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/CLLocationManagerDelegate-Implementations","title":"CLLocationManagerDelegate Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"locationManagerDidChangeAuthorization:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"locationManagerDidChangeAuthorization:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"locationManagerDidChangeAuthorization:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CLLocationManager","preciseIdentifier":"c:objc(cs)CLLocationManager","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"manager","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/title","op":"replace","value":"Account"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/fragments","op":"replace","value":[{"kind":"identifier","text":"Account"}]},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"Account"}]},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account~1locationManagerDidChangeAuthorization(_:)\/title","op":"replace","value":"locationManagerDidChangeAuthorization:"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account~1locationManagerDidChangeAuthorization(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"locationManagerDidChangeAuthorization:","kind":"identifier"}]}]}]}