{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account"]]},"metadata":{"title":"setOnStatusListener(_:)","role":"symbol","externalID":"s:12self_ios_sdk7AccountC19setOnStatusListeneryyys6UInt64VcF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setOnStatusListener"},{"kind":"text","text":"((("},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"self_ios_sdk"}]},"abstract":[{"type":"text","text":"setOnStatusListener"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setOnStatusListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"onStatus"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" (("},{"kind":"typeIdentifier","text":"UInt64","preciseIdentifier":"s:s6UInt64V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":"))"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"onStatus","content":[{"inlineContent":[{"text":"Succeed when status = 0","type":"text"}],"type":"paragraph"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/setOnStatusListener(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/self_ios_sdk\/account\/setonstatuslistener(_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.joinself.sdk/documentation/self_ios_sdk/Account":{"abstract":[{"text":"Create Self Account","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Account","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/account","title":"Account","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","kind":"symbol","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","url":"\/documentation\/self_ios_sdk","abstract":[],"title":"self_ios_sdk","kind":"symbol","role":"collection"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/setOnStatusListener(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setOnStatusListener","kind":"identifier"},{"text":"(((","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":"))","kind":"text"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/setOnStatusListener(_:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"setOnStatusListener"}],"url":"\/documentation\/self_ios_sdk\/account\/setonstatuslistener(_:)","title":"setOnStatusListener(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"Account","path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Account"}],"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Account"}],"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}