{"identifier":{"url":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Create Self Account","type":"text"}],"kind":"symbol","topicSections":[{"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/Builder"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/addResponseListenerForRequest(id:callback:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/aliasCredential(identifierAddress:info:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/backup()","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/close()","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/connectWith(address:info:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/connectWith(qrCode:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/credentials()","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/credentialsByType()","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/decryptNotification(forAddress:payload:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/generateAddress()","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/get(key:credentials:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/handleSignInRequestForSDK(deviceId:publicKeyBase64:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/location()","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/lookUpCredentials(claims:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/presentationForAddress(forAddress:credentials:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/qrCode()","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/qrCode(data:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/register(selfieImage:credentials:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/register(selfieImage:forAddress:presentation:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/registered()","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/restore(backupFile:selfieImage:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/send(message:onAcknowledgement:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/setOnInfoRequest(_:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/setOnInfoResponse(_:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/setOnMessageListener(_:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/setOnRelayConnectListener(_:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/setOnRequestListener(_:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/setOnResponseListener(_:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/setOnStatusListener(_:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/store(keyValue:)"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/CLLocationManagerDelegate-Implementations"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/self_ios_sdk\/account"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/self_ios_sdk\/account"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Account"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk"]]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.joinself.sdk\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.joinself.sdk\/objc(pl)CLLocationManagerDelegate","doc:\/\/com.joinself.sdk\/objc(pl)NSObject","doc:\/\/com.joinself.sdk\/s7CVarArgP","doc:\/\/com.joinself.sdk\/s8CopyableP","doc:\/\/com.joinself.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.joinself.sdk\/s23CustomStringConvertibleP","doc:\/\/com.joinself.sdk\/SQ","doc:\/\/com.joinself.sdk\/SH"]}],"metadata":{"externalID":"c:@M@self_ios_sdk@objc(cs)Account","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"self_ios_sdk"}],"role":"symbol","roleHeading":"Class","title":"Account","navigatorTitle":[{"kind":"identifier","text":"Account"}]},"references":{"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/restore(backupFile:selfieImage:)":{"kind":"symbol","url":"\/documentation\/self_ios_sdk\/account\/restore(backupfile:selfieimage:)","abstract":[{"text":"restore from self_backup file","type":"text"}],"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/restore(backupFile:selfieImage:)","role":"symbol","title":"restore(backupFile:selfieImage:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"restore","kind":"identifier"},{"text":"(","kind":"text"},{"text":"backupFile","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"selfieImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/close()":{"abstract":[{"text":"gracefully closes all storage and websocket connections","type":"text"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/close()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"close","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"role":"symbol","title":"close()","type":"topic","url":"\/documentation\/self_ios_sdk\/account\/close()"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/connectWith(qrCode:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"qrCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"}],"kind":"symbol","type":"topic","title":"connectWith(qrCode:)","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/connectWith(qrCode:)","url":"\/documentation\/self_ios_sdk\/account\/connectwith(qrcode:)","abstract":[],"role":"symbol"},"doc://com.joinself.sdk/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/com.joinself.sdk\/s8CopyableP","type":"unresolvable"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/register(selfieImage:credentials:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"("},{"kind":"externalParam","text":"selfieImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"credentials"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:12self_ios_sdk10CredentialC","text":"Credential"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"text":"Registers an account in Self network.","type":"text"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/register(selfieImage:credentials:)","type":"topic","title":"register(selfieImage:credentials:)","url":"\/documentation\/self_ios_sdk\/account\/register(selfieimage:credentials:)"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/setOnResponseListener(_:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/self_ios_sdk\/account\/setonresponselistener(_:)","abstract":[{"text":"setOnResponseListener","type":"text"}],"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/setOnResponseListener(_:)","title":"setOnResponseListener(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setOnResponseListener","kind":"identifier"},{"text":"(((","kind":"text"},{"preciseIdentifier":"s:12self_ios_sdk7MessageP","text":"Message","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/register(selfieImage:forAddress:presentation:)":{"kind":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/register(selfieImage:forAddress:presentation:)","url":"\/documentation\/self_ios_sdk\/account\/register(selfieimage:foraddress:presentation:)","title":"register(selfieImage:forAddress:presentation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"("},{"kind":"externalParam","text":"selfieImage"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"presentation"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","type":"topic","abstract":[]},"doc://com.joinself.sdk/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.joinself.sdk\/s23CustomStringConvertibleP"},"doc://com.joinself.sdk/objc(pl)CLLocationManagerDelegate":{"title":"CLLocationManagerDelegate","identifier":"doc:\/\/com.joinself.sdk\/objc(pl)CLLocationManagerDelegate","type":"unresolvable"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/generateAddress()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateAddress"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"url":"\/documentation\/self_ios_sdk\/account\/generateaddress()","role":"symbol","title":"generateAddress()","kind":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/generateAddress()","type":"topic","abstract":[]},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account":{"abstract":[{"text":"Create Self Account","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Account","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/account","title":"Account","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account","kind":"symbol","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/qrCode()":{"url":"\/documentation\/self_ios_sdk\/account\/qrcode()","title":"qrCode()","role":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/qrCode()","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qrCode","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"abstract":[{"type":"text","text":"get qrcode svg data"}]},"doc://com.joinself.sdk/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.joinself.sdk\/s28CustomDebugStringConvertibleP"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/send(message:onAcknowledgement:)":{"title":"send(message:onAcknowledgement:)","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/send(message:onAcknowledgement:)","type":"topic","url":"\/documentation\/self_ios_sdk\/account\/send(message:onacknowledgement:)","abstract":[{"text":"Encrypts and sends a message to the messages recipient onAcknowledgement is invoked when a response is received from the server.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"send","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Message","preciseIdentifier":"s:12self_ios_sdk7MessageP","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onAcknowledgement","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","kind":"symbol"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/credentialsByType()":{"url":"\/documentation\/self_ios_sdk\/account\/credentialsbytype()","abstract":[],"title":"credentialsByType()","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"credentialsByType"},{"kind":"text","text":"() -> ["},{"preciseIdentifier":"s:12self_ios_sdk17CredentialsByTypeV","kind":"typeIdentifier","text":"CredentialsByType"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/credentialsByType()","role":"symbol"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/presentationForAddress(forAddress:credentials:)":{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/presentationForAddress(forAddress:credentials:)","title":"presentationForAddress(forAddress:credentials:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationForAddress"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"credentials"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:12self_ios_sdk10CredentialC","text":"Credential"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"url":"\/documentation\/self_ios_sdk\/account\/presentationforaddress(foraddress:credentials:)","type":"topic","kind":"symbol","role":"symbol","abstract":[]},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/lookUpCredentials(claims:)":{"type":"topic","title":"lookUpCredentials(claims:)","kind":"symbol","url":"\/documentation\/self_ios_sdk\/account\/lookupcredentials(claims:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"lookUpCredentials"},{"kind":"text","text":"("},{"kind":"externalParam","text":"claims"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:12self_ios_sdk5ClaimC","kind":"typeIdentifier","text":"Claim"},{"kind":"text","text":"]) -> ["},{"preciseIdentifier":"s:12self_ios_sdk10CredentialC","kind":"typeIdentifier","text":"Credential"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/lookUpCredentials(claims:)"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/decryptNotification(forAddress:payload:)":{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/decryptNotification(forAddress:payload:)","title":"decryptNotification(forAddress:payload:)","url":"\/documentation\/self_ios_sdk\/account\/decryptnotification(foraddress:payload:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decryptNotification"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forAddress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"payload"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:12self_ios_sdk12NotificationC","text":"Notification"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/Builder":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Builder"}],"title":"Account.Builder","type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/Builder","url":"\/documentation\/self_ios_sdk\/account\/builder","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Builder"}]},"doc://com.joinself.sdk/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.joinself.sdk\/SH"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/get(key:credentials:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"get"},{"kind":"text","text":"("},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"credentials"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:12self_ios_sdk10CredentialC","text":"Credential"},{"text":"]) -> ","kind":"text"},{"text":"KeyValue","kind":"typeIdentifier","preciseIdentifier":"s:12self_ios_sdk8KeyValueC"},{"text":"?","kind":"text"}],"title":"get(key:credentials:)","url":"\/documentation\/self_ios_sdk\/account\/get(key:credentials:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/get(key:credentials:)","abstract":[{"text":"get value data by key","type":"text"}],"type":"topic"},"doc://com.joinself.sdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.joinself.sdk\/SQ","type":"unresolvable"},"doc://com.joinself.sdk/documentation/self_ios_sdk":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","url":"\/documentation\/self_ios_sdk","abstract":[],"title":"self_ios_sdk","kind":"symbol","role":"collection"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/addResponseListenerForRequest(id:callback:)":{"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addResponseListenerForRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"callback","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Any","kind":"keyword"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/addResponseListenerForRequest(id:callback:)","type":"topic","abstract":[],"title":"addResponseListenerForRequest(id:callback:)","url":"\/documentation\/self_ios_sdk\/account\/addresponselistenerforrequest(id:callback:)"},"doc://com.joinself.sdk/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.joinself.sdk\/objc(cs)NSObject"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/qrCode(data:)":{"kind":"symbol","title":"qrCode(data:)","url":"\/documentation\/self_ios_sdk\/account\/qrcode(data:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"qrCode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:12self_ios_sdk13DiscoveryDataV","kind":"typeIdentifier","text":"DiscoveryData"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"parse qrcode data"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/qrCode(data:)"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/store(keyValue:)":{"url":"\/documentation\/self_ios_sdk\/account\/store(keyvalue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"store"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:12self_ios_sdk8KeyValueC","kind":"typeIdentifier","text":"KeyValue"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"store key value data in PDS"}],"role":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/store(keyValue:)","type":"topic","title":"store(keyValue:)","kind":"symbol"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/credentials()":{"title":"credentials()","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/credentials()","url":"\/documentation\/self_ios_sdk\/account\/credentials()","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"credentials"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:12self_ios_sdk10CredentialC","text":"Credential"},{"kind":"text","text":"]"}],"abstract":[{"text":"lists all attestations held in the pds","type":"text"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/aliasCredential(identifierAddress:info:)":{"title":"aliasCredential(identifierAddress:info:)","url":"\/documentation\/self_ios_sdk\/account\/aliascredential(identifieraddress:info:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"aliasCredential"},{"kind":"text","text":"("},{"kind":"externalParam","text":"identifierAddress"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}],"abstract":[],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/aliasCredential(identifierAddress:info:)","role":"symbol"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/setOnStatusListener(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setOnStatusListener","kind":"identifier"},{"text":"(((","kind":"text"},{"preciseIdentifier":"s:s6UInt64V","text":"UInt64","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":"))","kind":"text"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/setOnStatusListener(_:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"setOnStatusListener"}],"url":"\/documentation\/self_ios_sdk\/account\/setonstatuslistener(_:)","title":"setOnStatusListener(_:)"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/connectWith(address:info:)":{"title":"connectWith(address:info:)","url":"\/documentation\/self_ios_sdk\/account\/connectwith(address:info:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectWith"},{"kind":"text","text":"("},{"kind":"externalParam","text":"address"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"async"},{"kind":"text","text":" "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/connectWith(address:info:)","role":"symbol"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/registered()":{"abstract":[],"url":"\/documentation\/self_ios_sdk\/account\/registered()","role":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/registered()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registered","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","title":"registered()"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/setOnRelayConnectListener(_:)":{"title":"setOnRelayConnectListener(_:)","url":"\/documentation\/self_ios_sdk\/account\/setonrelayconnectlistener(_:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setOnRelayConnectListener"},{"kind":"text","text":"((() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/setOnRelayConnectListener(_:)","role":"symbol"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/setOnInfoResponse(_:)":{"kind":"symbol","title":"setOnInfoResponse(_:)","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/setOnInfoResponse(_:)","role":"symbol","abstract":[{"text":"receive user info from sdk","type":"text"}],"type":"topic","url":"\/documentation\/self_ios_sdk\/account\/setoninforesponse(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setOnInfoResponse","kind":"identifier"},{"text":"(((","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":"))","kind":"text"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/setOnInfoRequest(_:)":{"title":"setOnInfoRequest(_:)","url":"\/documentation\/self_ios_sdk\/account\/setoninforequest(_:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setOnInfoRequest","kind":"identifier"},{"text":"(((","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?))","kind":"text"}],"abstract":[{"type":"text","text":"send user info to sdk"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/setOnInfoRequest(_:)","role":"symbol"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/setOnMessageListener(_:)":{"title":"setOnMessageListener(_:)","url":"\/documentation\/self_ios_sdk\/account\/setonmessagelistener(_:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setOnMessageListener","kind":"identifier"},{"text":"(((","kind":"text"},{"text":"Message","kind":"typeIdentifier","preciseIdentifier":"s:12self_ios_sdk7MessageP"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"abstract":[{"text":"setOnMessageListener","type":"text"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/setOnMessageListener(_:)","role":"symbol"},"doc://com.joinself.sdk/s7CVarArgP":{"identifier":"doc:\/\/com.joinself.sdk\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/backup()":{"title":"backup()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backup","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/backup()","url":"\/documentation\/self_ios_sdk\/account\/backup()","kind":"symbol","abstract":[{"text":"backup data in PDS into a ","type":"text"},{"code":".self_backup","type":"codeVoice"},{"text":" zip file","type":"text"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/location()":{"title":"location()","url":"\/documentation\/self_ios_sdk\/account\/location()","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"location","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"Credential","kind":"typeIdentifier","preciseIdentifier":"s:12self_ios_sdk10CredentialC"},{"text":"]","kind":"text"}],"abstract":[{"text":"request location and wait for the result","type":"text"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/location()","role":"symbol"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/setOnRequestListener(_:)":{"title":"setOnRequestListener(_:)","type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/setOnRequestListener(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setOnRequestListener","kind":"identifier"},{"text":"(((","kind":"text"},{"text":"Message","kind":"typeIdentifier","preciseIdentifier":"s:12self_ios_sdk7MessageP"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?)","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"setOnRequestListener"}],"url":"\/documentation\/self_ios_sdk\/account\/setonrequestlistener(_:)","kind":"symbol"},"doc://com.joinself.sdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.joinself.sdk\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/CLLocationManagerDelegate-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/self_ios_sdk\/account\/cllocationmanagerdelegate-implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/CLLocationManagerDelegate-Implementations","title":"CLLocationManagerDelegate Implementations"},"doc://com.joinself.sdk/documentation/self_ios_sdk/Account/handleSignInRequestForSDK(deviceId:publicKeyBase64:)":{"title":"handleSignInRequestForSDK(deviceId:publicKeyBase64:)","type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/handleSignInRequestForSDK(deviceId:publicKeyBase64:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"handleSignInRequestForSDK","kind":"identifier"},{"text":"(","kind":"text"},{"text":"deviceId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"publicKeyBase64","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","abstract":[{"text":"add new device for existing selfId","type":"text"}],"url":"\/documentation\/self_ios_sdk\/account\/handlesigninrequestforsdk(deviceid:publickeybase64:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"Account","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"Account","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Account"}],"op":"replace"},{"op":"replace","value":[{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/Account\/CLLocationManagerDelegate-Implementations"],"anchor":"Default-Implementations"}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.joinself.sdk\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.joinself.sdk\/objc(pl)CLLocationManagerDelegate"],"type":"conformsTo"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Account","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/title","op":"replace","value":"Account"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/fragments","op":"replace","value":[{"text":"Account","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1Account\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"Account"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}