{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/self_ios_sdk\/livenesscheck"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/self_ios_sdk\/livenesscheck"]}],"hierarchy":{"paths":[["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk"]]},"topicSections":[{"identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/ChallengeState"],"title":"Classes","generated":true,"anchor":"Classes"},{"identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/init()","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/init(account:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/currentChallenge","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/isVerificationRequired","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/onChallengeChanged","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/onResult","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/onStatusUpdated","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/properties"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/getAttemptsNumber()","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/handleImageBuffer(sampleBuffer:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/initialize(account:cameraView:)","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/setupAndStart()","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/start()","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/stop()"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Challenge","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Error","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Status"],"title":"Enumerations","generated":true,"anchor":"Enumerations"},{"identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations","doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/ObservableObject-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"metadata":{"modules":[{"name":"self_ios_sdk"}],"symbolKind":"class","roleHeading":"Class","role":"symbol","title":"LivenessCheck","navigatorTitle":[{"text":"LivenessCheck","kind":"identifier"}],"externalID":"c:@M@self_ios_sdk@objc(cs)LivenessCheck","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivenessCheck","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivenessCheck","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/com.joinself.sdk\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/com.joinself.sdk\/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate","doc:\/\/com.joinself.sdk\/7Combine16ObservableObjectP","doc:\/\/com.joinself.sdk\/objc(pl)NSObject","doc:\/\/com.joinself.sdk\/s7CVarArgP","doc:\/\/com.joinself.sdk\/s8CopyableP","doc:\/\/com.joinself.sdk\/s28CustomDebugStringConvertibleP","doc:\/\/com.joinself.sdk\/s23CustomStringConvertibleP","doc:\/\/com.joinself.sdk\/SQ","doc:\/\/com.joinself.sdk\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck"},"sections":[],"kind":"symbol","references":{"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/initialize(account:cameraView:)":{"title":"initialize(account:cameraView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"account"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)Account","text":"Account"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":")"}],"type":"topic","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/initialize(account:cameraView:)","url":"\/documentation\/self_ios_sdk\/livenesscheck\/initialize(account:cameraview:)"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/stop()":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/stop()","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/self_ios_sdk\/livenesscheck\/stop()","title":"stop()"},"doc://com.joinself.sdk/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.joinself.sdk\/SH"},"doc://com.joinself.sdk/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.joinself.sdk\/objc(cs)NSObject"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/init()":{"type":"topic","abstract":[],"role":"symbol","title":"init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/init()","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"url":"\/documentation\/self_ios_sdk\/livenesscheck\/init()"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/Challenge":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Challenge"}],"title":"LivenessCheck.Challenge","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Challenge"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Challenge","url":"\/documentation\/self_ios_sdk\/livenesscheck\/challenge"},"doc://com.joinself.sdk/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.joinself.sdk\/s7CVarArgP"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/handleImageBuffer(sampleBuffer:)":{"kind":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/handleImageBuffer(sampleBuffer:)","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/self_ios_sdk\/livenesscheck\/handleimagebuffer(samplebuffer:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleImageBuffer"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sampleBuffer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":")"}],"title":"handleImageBuffer(sampleBuffer:)"},"doc://com.joinself.sdk/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.joinself.sdk\/s23CustomStringConvertibleP"},"doc://com.joinself.sdk/documentation/self_ios_sdk":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk","url":"\/documentation\/self_ios_sdk","abstract":[],"title":"self_ios_sdk","kind":"symbol","role":"collection"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/ObservableObject-Implementations":{"title":"ObservableObject Implementations","url":"\/documentation\/self_ios_sdk\/livenesscheck\/observableobject-implementations","abstract":[],"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/ObservableObject-Implementations","role":"collectionGroup","kind":"article"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/setupAndStart()":{"title":"setupAndStart()","url":"\/documentation\/self_ios_sdk\/livenesscheck\/setupandstart()","kind":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/setupAndStart()","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setupAndStart","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[]},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/ChallengeState":{"kind":"symbol","type":"topic","url":"\/documentation\/self_ios_sdk\/livenesscheck\/challengestate","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ChallengeState"}],"title":"LivenessCheck.ChallengeState","role":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/ChallengeState","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChallengeState"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/isVerificationRequired":{"kind":"symbol","url":"\/documentation\/self_ios_sdk\/livenesscheck\/isverificationrequired","role":"symbol","abstract":[],"title":"isVerificationRequired","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isVerificationRequired","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/isVerificationRequired"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/init(account:)":{"type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/init(account:)","role":"symbol","url":"\/documentation\/self_ios_sdk\/livenesscheck\/init(account:)","kind":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"account"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)Account","kind":"typeIdentifier","text":"Account"},{"kind":"text","text":")"}],"title":"init(account:)"},"doc://com.joinself.sdk/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate":{"title":"AVCaptureVideoDataOutputSampleBufferDelegate","identifier":"doc:\/\/com.joinself.sdk\/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate","type":"unresolvable"},"doc://com.joinself.sdk/objc(pl)NSObject":{"identifier":"doc:\/\/com.joinself.sdk\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/Status":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"Status","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Status","kind":"identifier"}],"title":"LivenessCheck.Status","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Status","url":"\/documentation\/self_ios_sdk\/livenesscheck\/status","abstract":[],"role":"symbol"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/onResult":{"role":"symbol","kind":"symbol","url":"\/documentation\/self_ios_sdk\/livenesscheck\/onresult","title":"onResult","abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onResult","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", [","kind":"text"},{"text":"Credential","kind":"typeIdentifier","preciseIdentifier":"s:12self_ios_sdk10CredentialC"},{"text":"], ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:12self_ios_sdk13LivenessCheckC5ErrorO"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/onResult"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations":{"abstract":[],"kind":"article","type":"topic","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations","role":"collectionGroup","url":"\/documentation\/self_ios_sdk\/livenesscheck\/avcapturevideodataoutputsamplebufferdelegate-implementations","title":"AVCaptureVideoDataOutputSampleBufferDelegate Implementations"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/currentChallenge":{"kind":"symbol","type":"topic","url":"\/documentation\/self_ios_sdk\/livenesscheck\/currentchallenge","abstract":[],"title":"currentChallenge","role":"symbol","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/currentChallenge","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentChallenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LivenessCheck","preciseIdentifier":"c:@M@self_ios_sdk@objc(cs)LivenessCheck"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ChallengeState","preciseIdentifier":"s:12self_ios_sdk13LivenessCheckC14ChallengeStateC"}]},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/start()":{"title":"start()","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/start()","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"()"}],"kind":"symbol","url":"\/documentation\/self_ios_sdk\/livenesscheck\/start()"},"doc://com.joinself.sdk/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.joinself.sdk\/SQ","type":"unresolvable"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/properties":{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/properties","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"properties"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]"}],"title":"properties","type":"topic","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/self_ios_sdk\/livenesscheck\/properties"},"doc://com.joinself.sdk/7Combine16ObservableObjectP":{"identifier":"doc:\/\/com.joinself.sdk\/7Combine16ObservableObjectP","type":"unresolvable","title":"Combine.ObservableObject"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/onStatusUpdated":{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/onStatusUpdated","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onStatusUpdated","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"Status","preciseIdentifier":"s:12self_ios_sdk13LivenessCheckC6StatusO","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"title":"onStatusUpdated","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/self_ios_sdk\/livenesscheck\/onstatusupdated"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/onChallengeChanged":{"type":"topic","kind":"symbol","role":"symbol","title":"onChallengeChanged","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onChallengeChanged","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"Challenge","kind":"typeIdentifier","preciseIdentifier":"s:12self_ios_sdk13LivenessCheckC9ChallengeO"},{"text":", ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:12self_ios_sdk13LivenessCheckC5ErrorO"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"url":"\/documentation\/self_ios_sdk\/livenesscheck\/onchallengechanged","abstract":[],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/onChallengeChanged"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/getAttemptsNumber()":{"abstract":[],"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/getAttemptsNumber()","url":"\/documentation\/self_ios_sdk\/livenesscheck\/getattemptsnumber()","kind":"symbol","title":"getAttemptsNumber()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getAttemptsNumber","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","role":"symbol"},"doc://com.joinself.sdk/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/com.joinself.sdk\/s8CopyableP","type":"unresolvable"},"doc://com.joinself.sdk/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.joinself.sdk\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck":{"title":"LivenessCheck","identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivenessCheck","kind":"identifier"}],"navigatorTitle":[{"text":"LivenessCheck","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/self_ios_sdk\/livenesscheck","type":"topic"},"doc://com.joinself.sdk/documentation/self_ios_sdk/LivenessCheck/Error":{"identifier":"doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/Error","type":"topic","role":"symbol","title":"LivenessCheck.Error","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/self_ios_sdk\/livenesscheck\/error"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"LivenessCheck","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LivenessCheck"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"LivenessCheck","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/init()"],"generated":true,"title":"Instance Methods"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/com.joinself.sdk\/documentation\/self_ios_sdk\/LivenessCheck\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations"],"generated":true,"title":"Default Implementations"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.joinself.sdk\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.joinself.sdk\/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate"],"kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LivenessCheck","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck~1init()\/title","value":"init","op":"replace"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/title","value":"LivenessCheck","op":"replace"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/fragments","value":[{"kind":"identifier","text":"LivenessCheck"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.joinself.sdk~1documentation~1self_ios_sdk~1LivenessCheck\/navigatorTitle","value":[{"text":"LivenessCheck","kind":"identifier"}],"op":"replace"}]}]}